version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: aurora-postgres
    environment:
      POSTGRES_USER: aurora
      POSTGRES_PASSWORD: aurora_dev
      POSTGRES_DB: aurora
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aurora"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aurora-network

  redis:
    image: redis:7-alpine
    container_name: aurora-redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aurora-network

volumes:
  postgres_data:

networks:
  aurora-network:
    driver: bridge
